self._1cc3633c579a90cfdd895e64021e2163 = self._1cc3633c579a90cfdd895e64021e2163 || {};(function(__c){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var r,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},u=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},v=function(a){if(!(a instanceof Array)){a=u(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=
a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},y=function(a,b){if(b)a:{var c=x;a=a.split(".");for(var d=0;d<a.length-1;d++){var k=a[d];if(!(k in c))break a;c=c[k]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}},fa=function(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(ea)ea(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,
c,d)}else a[c]=b[c];a.Nb=b.prototype},ha=function(){this.pa=!1;this.T=null;this.Da=void 0;this.C=1;this.Za=this.W=0;this.U=null},ia=function(a){if(a.pa)throw new TypeError("Generator is already running");a.pa=!0},z=function(a,b,c){a.C=c;return{value:b}},ja=function(a){a.C=3;a.W=0},ka=function(a){a.W=0;var b=a.U.Wa;a.U=null;return b},la=function(a){this.j=new ha;this.Bb=a},oa=function(a,b){ia(a.j);var c=a.j.T;if(c)return ma(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.j.return);
a.j.return(b);return na(a)},ma=function(a,b,c,d){try{var k=b.call(a.j.T,c);if(!(k instanceof Object))throw new TypeError("Iterator result "+k+" is not an object");if(!k.done)return a.j.pa=!1,k;var m=k.value}catch(f){return a.j.T=null,a.j.ua(f),na(a)}a.j.T=null;d.call(a.j,m);return na(a)},na=function(a){for(;a.j.C;)try{var b=a.Bb(a.j);if(b)return a.j.pa=!1,{value:b.value,done:!1}}catch(c){a.j.Da=void 0,a.j.ua(c)}a.j.pa=!1;if(a.j.U){b=a.j.U;a.j.U=null;if(b.ub)throw b.Wa;return{value:b.return,done:!0}}return{value:void 0,
done:!0}},pa=function(a){this.next=function(b){return a.qa(b)};this.throw=function(b){return a.ua(b)};this.return=function(b){return oa(a,b)};this[Symbol.iterator]=function(){return this}},A=function(a,b){b=new pa(new la(b));ea&&a.prototype&&ea(b,a.prototype);return b},qa=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},ra=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,k={next:function(){if(!d&&c<a.length){var m=c++;return{value:b(m,a[m]),done:!1}}d=!0;return{done:!0,
value:void 0}}};k[Symbol.iterator]=function(){return k};return k},B=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},sa=function(){},E=function(a,b,c){for(var d=[],k=2;k<arguments.length;++k)d[k-2]=arguments[k];if(!a)throw Error(null==b?"invalid argument":ta.apply(sa,[b].concat(v(d))));},ua=function(a,b,c){for(var d=[],k=2;k<arguments.length;++k)d[k-2]=arguments[k];if(!a)throw Error(null==b?"invalid state":ta.apply(sa,[b].concat(v(d))));},F=function(a,b,c){for(var d=[],k=2;k<arguments.length;++k)d[k-
2]=arguments[k];if(null==a)throw Error(null==b?"argument is null":ta.apply(sa,[b].concat(v(d))));return a},ta=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];var k=0;return a.replace(/\{}/g,function(){return k<c.length?c[k++]:"{}"})},G=function(a){a=Error.call(this,"unhandled case: "+JSON.stringify(a));this.message=a.message;"stack"in a&&(this.stack=a.stack)},H=function(a,b){return{type:1,g:"A?",Ka:a,value:b}},va=function(a){return{type:2,g:a,default:void 0}},I=function(a){return{type:3,
g:a,Ba:void 0}},J=function(a){return{type:4,g:a,default:void 0}},K=function(a){return{type:5,g:a,Ba:void 0}},P=function(a){function b(k){k=void 0===k?{}:k;var m=d(),f=m.Ia;m=m.Xa;for(var h=0;h<m.length;++h){var e=f[h],l=m[h],g=k[e];switch(l.type){case 1:this[e]=l.value;break;case 6:case 4:case 2:case 8:case 10:this[e]=null==g?l.default:g;break;case 7:case 5:case 3:case 9:case 11:this[e]=g;break;case 16:case 15:case 13:case 12:case 14:this[e]=null==g?[]:g;break;case 17:this[e]=null==g?new Map:g;break;
default:throw new wa(l);}}}var c=void 0===c?{}:c;var d=xa(function(){var k=a(),m=Object.keys(k),f=m.map(function(h){return k[h]});return{Ya:k,Ia:m,Xa:f}});b.u=function(k){var m=d(),f=m.Ia;m=m.Xa;for(var h=Object.create(b.prototype),e=0;e<m.length;++e){var l=m[e],g=k[l.g];switch(l.type){case 1:if(l.Ka!==g)throw new TypeError("Expected value "+JSON.stringify(l.value)+" for property "+l.g+" found: "+JSON.stringify(g)+".");h[f[e]]=l.value;break;case 6:if(null==g)h[f[e]]=!1;else{if("boolean"!==typeof g)throw L(l.g,
g,"boolean");h[f[e]]=g}break;case 4:if(null==g||"string"!==typeof g)throw L(l.g,g,"string");h[f[e]]=g;break;case 2:if(null==g)h[f[e]]=0;else{if("number"!==typeof g)throw L(l.g,g,"number");h[f[e]]=g}break;case 7:if(null==g)h[f[e]]=void 0;else{if("boolean"!==typeof g)throw N(l.g,g,"boolean");h[f[e]]=g}break;case 5:if(null==g)h[f[e]]=void 0;else{if("string"!==typeof g)throw N(l.g,g,"string");h[f[e]]=g}break;case 3:if(null==g)h[f[e]]=void 0;else{if("number"!==typeof g)throw N(l.g,g,"number");h[f[e]]=
g}break;case 11:if(null==g)h[f[e]]=void 0;else if("object"===typeof g)h[f[e]]=l.u(g,l.g);else throw N(l.g,g,"object");break;case 10:if("object"===typeof g)h[f[e]]=l.u(g,l.g);else throw L(l.g,g,"number");break;case 8:if("string"===typeof g)h[f[e]]=l.u(g,l.g);else throw L(l.g,g,"string");break;case 9:if(null==g)h[f[e]]=void 0;else if("string"===typeof g)h[f[e]]=l.u(g,l.g);else throw N(l.g,g,"string");break;case 12:if(null==g)h[f[e]]=[];else if(Array.isArray(g)){for(var n=0;n<g.length;++n)if("number"!==
typeof g[n])throw L(l.g,g[n],"number");h[f[e]]=g}else throw O(l.g,g,"number");break;case 13:if(null==g)h[f[e]]=[];else if(Array.isArray(g)){for(n=0;n<g.length;++n)if("string"!==typeof g[n])throw L(l.g,g[n],"string");h[f[e]]=g}else throw O(l.g,g,"string");break;case 14:if(null==g)h[f[e]]=[];else if(Array.isArray(g)){for(n=0;n<g.length;++n)if("boolean"!==typeof g[n])throw L(l.g,g[n],"boolean");h[f[e]]=g}else throw O(l.g,g,"boolean");break;case 15:if(null==g)h[f[e]]=[];else if(Array.isArray(g)){n=Array(g.length);
for(var p=0;p<g.length;++p){if("string"!==typeof g[p])throw L(l.g,g[p],"string");n[p]=l.u(g[p],l.g)}h[f[e]]=n}else throw O(l.g,g,"string");break;case 16:if(null==g)h[f[e]]=[];else if(Array.isArray(g)){n=Array(g.length);for(p=0;p<g.length;++p){if("object"!==typeof g[p])throw L(l.g,g[p],"object");n[p]=l.u(g[p],l.g)}h[f[e]]=n}else throw O(l.g,g,"object");break;case 17:if(null==g)h[f[e]]=new Map;else{if("object"!==typeof g)throw new TypeError('expected Map for property "'+l.g+'", found: '+JSON.stringify(g));
n=Object.keys(g);p=Array(n.length);for(var q=0;q<n.length;++q){var t=n[q];if("number"===l.kb){var w=Number(t);if(isNaN(w))throw new TypeError('expected number key in property "'+l.g+'", found: '+JSON.stringify(t));}else w=t;if(typeof g[t]!==l.Ma)throw new TypeError("expected "+l.Ma+' value in property "'+l.g+'", found: '+JSON.stringify(g[t]));t=l.u?l.u(g[t]):g[t];p[q]=[w,t]}h[f[e]]=new Map(p)}break;default:throw new wa(l);}}return h};b.sb=function(){return d().Ya};b.D=c.Na?function(){throw new TypeError("uproducible oneof case");
}:function(k,m){if("object"!==typeof k)throw new TypeError("Expected type object for property "+m+" found: "+JSON.stringify(k));var f=d();m=f.Ya;var h={};f=u(f.Ia);for(var e=f.next();!e.done;e=f.next()){var l=e.value;e=m[l];var g=k[l];if(null==g&&e.Ba)throw new TypeError(e.g+" is required for producers");switch(e.type){case 1:if(g!==e.value)throw new TypeError("Expected value "+JSON.stringify(e.value)+" found: "+JSON.stringify(g)+".");h[e.g]=e.Ka;break;case 10:g=e.D(g,e.g);if("object"!==typeof g)throw L(e.g,
g,"object");h[e.g]=g;break;case 8:g=e.D(g,e.g);if("string"!==typeof g)throw L(e.g,g,"string");h[e.g]=g;break;case 11:if(null!=g){g=e.D(g,e.g);if("object"!==typeof g)throw N(e.g,g,"object");h[e.g]=g}break;case 9:if(null!=g){g=e.D(g,e.g);if("string"!==typeof g)throw N(e.g,g,"string");h[e.g]=g}break;case 6:if(g){if("boolean"!==typeof g)throw L(e.g,g,"boolean");h[e.g]=g}break;case 2:if(g){if("number"!==typeof g)throw L(e.g,g,"number");h[e.g]=g}break;case 4:if("string"!==typeof g)throw L(e.g,g,"string");
h[e.g]=g;break;case 7:if(null!=g){if("boolean"!==typeof g)throw N(e.g,g,"boolean");h[e.g]=g}break;case 3:if(null!=g){if("number"!==typeof g)throw N(e.g,g,"number");h[e.g]=g}break;case 5:if(null!=g){if("string"!==typeof g)throw N(e.g,g,"string");h[e.g]=g}break;case 14:if(null!=g){if(!Array.isArray(g))throw O(e.g,g,"boolean");l=g.length;if(0<l){for(var n=0;n<l;++n)if("boolean"!==typeof g[n])throw L(e.g,g[n],"boolean");h[e.g]=g}}break;case 13:if(null!=g){if(!Array.isArray(g))throw O(e.g,g,"string");
l=g.length;if(0<l){for(n=0;n<l;++n)if("string"!==typeof g[n])throw L(e.g,g[n],"string");h[e.g]=g}}break;case 12:if(null!=g){if(!Array.isArray(g))throw O(e.g,g,"number");if(0<g.length){for(l=0;l<g.length;++l)if("number"!==typeof g[l])throw L(e.g,g[l],"number");h[e.g]=g}}break;case 16:if(null!=g){if(!Array.isArray(g))throw O(e.g,g,"object");if(0<g.length){l=Array(g.length);for(n=0;n<g.length;++n){var p=e.D(g[n],e.g);if("object"!==typeof p)throw L(e.g,g[n],"object");l[n]=p}h[e.g]=l}}break;case 15:if(null!=
g){if(!Array.isArray(g))throw O(e.g,g,"string");if(0<g.length){l=Array(g.length);for(n=0;n<g.length;++n){p=e.D(g[n],e.g);if("string"!==typeof p)throw L(e.g,g[n],"string");l[n]=p}h[e.g]=l}}break;case 17:if(!(g instanceof Map))throw new TypeError('expected Map for property "'+l+'", found: '+JSON.stringify(g));if(g.size){n={};p=e.D;g=u(g);for(var q=g.next();!q.done;q=g.next()){var t=u(q.value);q=t.next().value;t=t.next().value;if(typeof q!==e.kb)throw new TypeError("expected "+e.kb+' key in property "'+
l+'", found: '+JSON.stringify(q));t=p?p(t):t;if(typeof t!==e.Ma)throw new TypeError("expected "+e.Ma+' key in property "'+l+'", found: '+JSON.stringify(t));n[q]=t}h[e.g]=n}break;default:throw new wa(e);}}return h};return b},ya=function(a){var b=xa(function(){for(var c=a(),d=[],k=new Map,m=new Map,f=new Set,h=0;h<c.length;){var e=c[h++],l=c[h++],g=c[h];"object"===typeof g&&g.Na&&(f.add(e),h+=1);d.push(e);k.set(l,e);m.set(e,l)}return{values:d,Jb:m,Gb:k,Na:f.size?f:void 0}});return{values:function(){return b().values},
D:function(c,d){var k=b(),m=k.Na;k=k.Jb;if(m&&m.has(c))throw new TypeError("unproducible enum value: "+c);m=k.get(c);if(!m)throw d=d?"for property "+d:"",new TypeError("Unrecognized deserialized value "+JSON.stringify(c)+d);return m},u:function(c,d){var k=b().Gb.get(c);if(!k)throw d=d?"for property "+d:"",new TypeError("Unrecognized serialized value "+JSON.stringify(c)+d+".");return k}}},xa=function(a){var b;return function(){return b||(b=a())}},O=function(a,b,c){return new TypeError("expected repeated "+
c+' for property "'+a+'", found: '+JSON.stringify(b))},N=function(a,b,c){return new TypeError("expected optional "+c+' for property "'+a+'", found: '+JSON.stringify(b))},L=function(a,b,c){return new TypeError("expected "+c+' for property "'+a+'", found: '+JSON.stringify(b))},wa=function(a){a=Error.call(this,"unhandled case: "+JSON.stringify(a));this.message=a.message;"stack"in a&&(this.stack=a.stack)},za=function(a,b){this.mb=a;this.origin=b;this.Ha=[]},Aa=function(a,b){a.Ha.includes(b)||a.Ha.push(b)},
Ca=function(a,b){var c=b.origin,d=b.data;d.__design_button_message__&&a.origin===c&&a.Ha.map(function(k){return k(Ba.u(d.__design_button_message__))})},Da=function(a,b){var c={},d;for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&0>b.indexOf(d)&&(c[d]=a[d]);if(null!=a&&"function"===typeof Object.getOwnPropertySymbols){var k=0;for(d=Object.getOwnPropertySymbols(a);k<d.length;k++)0>b.indexOf(d[k])&&Object.prototype.propertyIsEnumerable.call(a,d[k])&&(c[d[k]]=a[d[k]])}return c},Ea=function(a,b,c){this.S=
a;this.H=b;this.l=c;this.ga=!1},Fa=function(a,b){a.onDesignClose=b.onDesignClose;a.onDesignOpen=b.onDesignOpen;a.onDesignPublish=b.onDesignPublish;a.onError=b.onError},Q=function(a){ua(a.ga,"startListening has not been called")},Ga=function(a,b){this.window=a;this.F=b},Ha=function(a,b){var c={};a.window.postMessage((c.__design_button_message__=Ba.D(b),c),a.F)},Ia=function(a){var b=this,c=a.L,d=a.ca,k=a.X;a=a.Aa;this.ja=function(){b.L.className="jbNFPA _6cWMPA";var m=F(b.fa);document.body.classList.add("CHM3WQ");
m.className="pC-ENQ lyePVA";m.onload=null;b.Aa.style.display="none";b.xa=new Ga(F(m.contentWindow),m.src)};this.L=c;this.X=k;this.Aa=a;this.ca=d;this.X&&this.X.addEventListener("click",function(){b.bb&&b.bb()})},Ja=function(a,b){a.bb=b},Ka=function(a,b){a.fa&&(a.ca.removeChild(a.fa),a.fa=void 0);var c=document.createElement("iframe");c.setAttribute("allowfullscreen","");a.fa=c;c.className="lyePVA";c.src=b;a.ca.appendChild(c)},La=function(a){var b=a.fa,c=a.L,d=a.Aa;document.body.classList.add("CHM3WQ");
c.className="jbNFPA _6cWMPA";F(b).className="LuEXOQ lyePVA";F(b).onload=a.ja;d.style.display="block"},R=function(a){var b,c=a.L,d=F(a.fa);d.onload=null;d.src="about:blank";d=getComputedStyle(c);var k=d.transitionDuration;if("none"===d.transitionProperty||"0s"===k)c.className="_6cWMPA";else{c.className="zuSYnw _6cWMPA";var m=function(){c.className="_6cWMPA";Ma.forEach(function(f){c.removeEventListener(f,m)})};Ma.forEach(function(f){c.addEventListener(f,m)});document.body.classList.remove("CHM3WQ");
null===(b=a.xa)||void 0===b?void 0:Ha(b,new Na)}},Oa=function(a){var b=void 0===a.B?"global":a.B,c=void 0===a.Qa?!0:a.Qa,d=void 0===a.Pa?!0:a.Pa,k=void 0===a.Oa?!0:a.Oa,m=document.createElement("div");m.setAttribute("dir",a.dir);m.className="_6cWMPA";if(c){a=d;a=void 0===a?!1:a;d=document.createElement("div");d.className="AyyjgQ";m.appendChild(d);if(a){var f=document.createElement("span");f.className="oA9Mcg";f.innerHTML='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 90 90"><path fill="#fff" d="M49 45l14-14c.5-.5.8-1.3.9-2 .1-.8-.2-1.6-.7-2.1s-1.3-.8-2.1-.7c-.8 0-1.5.4-2 .9l-14 14-14-14c-.5-.5-1.3-.8-2-.9-.8-.1-1.6.2-2.1.7s-.8 1.3-.7 2.1c0 .8.4 1.5.9 2l14 14-14 14c-.5.5-.8 1.3-.9 2-.1.8.2 1.6.7 2.1s1.3.8 2.1.7c.8 0 1.5-.4 2-.9l14-14 14 14c.5.5 1.3.8 2 .9.8.1 1.6-.2 2.1-.7s.8-1.3.7-2.1c0-.8-.4-1.5-.9-2L49 45z"/></svg>';
d.appendChild(f)}f={ca:d,X:f}}else f={ca:m};a=f;f=a.ca;a=void 0===a.X?void 0:a.X;d=document.createElement("div");k||c?d.classList.add.apply(d.classList,v(["_2721_Q","ImojUQ"].concat("china"===b?["l2qO1Q"]:["IEy-yQ"]))):(d.className="bcCxmA ImojUQ",d.innerHTML="\n        <div class=Smf5Xg>\n        <div class=As2zUA></div>\n        <div class=tMP-jQ>\n          <div class=HdsXQA></div>\n          <div class=n-337w></div>\n          <div class=yIE6Jg>\n            <div class=BIUa3g></div>\n          </div>\n        </div>\n        </div>\n      ");
f.appendChild(d);return new Ia({L:m,ca:f,X:a,Aa:d})},Qa=function(){return Pa.includes(window.navigator.language)},Ra=function(a){return null!=a},Sa=function(a){this.path=a;this.ia=new Map},T=function(){var a=["_partnership","embed"];E(0<a.length);E(a.every(function(b){return 0>b.indexOf("?")}));return S(new Sa([""].concat(v(a.map(encodeURIComponent))).join("/")),void 0)},S=function(a,b){if(!b)return a;if(b instanceof Map){b=u(b);for(var c=b.next();!c.done;c=b.next()){var d=u(c.value);c=d.next().value;
d=d.next().value;U(a,c,d)}}else for(c in b)U(a,c,b[c]);return a},U=function(a,b,c){E(0<b.length);E(!a.ia.has(b));if(null!=c)if(Array.isArray(c)){c=c.filter(Ra);if(0===c.length)return a;E(c.every(function(d){return"number"===typeof d||"string"===typeof d}));a.ia.set(b,c)}else if("boolean"===typeof c)a.ia.set(b,c||String(c));else if("number"===typeof c||"string"===typeof c)a.ia.set(b,String(c));else throw Error("invalid param value type: "+typeof c);return a},V=function(a){if(0===a.ia.size)return a.path;
var b=Array.from(a.ia.entries()).map(function(c){c=u(c);var d=c.next().value;c=c.next().value;return!0===c?""+encodeURIComponent(d):Array.isArray(c)?c.map(function(k){return encodeURIComponent(d)+"="+encodeURIComponent(k)}).join("&"):encodeURIComponent(d)+"="+encodeURIComponent(c)}).join("&");return a.path+"?"+b},W=function(a,b,c,d,k){this.O=a;this.apiKey=b;this.origin=c;this.Ea=d;this.autoAuthToken=k},Ta=function(a,b){function c(k){return k instanceof d?k:new d(function(m){m(k)})}var d=void 0;return new (d||
(d=Promise))(function(k,m){function f(l){try{e(b.next(l))}catch(g){m(g)}}function h(l){try{e(b["throw"](l))}catch(g){m(g)}}function e(l){l.done?k(l.value):c(l.value).then(f,h)}e((b=b.apply(a,[])).next())})},Ua=function(a,b){var c={},d;for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&0>b.indexOf(d)&&(c[d]=a[d]);if(null!=a&&"function"===typeof Object.getOwnPropertySymbols){var k=0;for(d=Object.getOwnPropertySymbols(a);k<d.length;k++)0>b.indexOf(d[k])&&Object.prototype.propertyIsEnumerable.call(a,
d[k])&&(c[d[k]]=a[d[k]])}return c},Ya=function(){var a=Va,b=window.location.origin,c=Wa,d=Xa;this.state=0;this.F=a;this.Y=b;this.K=c;this.B=d},Za=function(a,b){console.warn("[CanvaButton] Looks like your are using "+a+", it will be removed after beta phase, please use "+(b+" instead."))},$a=function(a,b){function c(k){return k instanceof d?k:new d(function(m){m(k)})}var d=void 0;return new (d||(d=Promise))(function(k,m){function f(l){try{e(b.next(l))}catch(g){m(g)}}function h(l){try{e(b["throw"](l))}catch(g){m(g)}}
function e(l){l.done?k(l.value):c(l.value).then(f,h)}e((b=b.apply(a,[])).next())})},ab=function(){var a=Va,b=window.location.origin,c=Wa,d=Xa;this.state=0;this.F=a;this.Y=b;this.K=c;this.B=d},bb=function(a,b,c){this.S=a;this.H=b;this.l=c;this.ga=!1},X=function(a,b,c,d,k){this.O=a;this.apiKey=b;this.origin=c;this.Ea=d;this.autoAuthToken=k},cb=function(a,b){return a.O+V(S(U(U(T(),"action","catalog"),"supportSavedDesigns",b),a.R))},db=function(a,b){function c(k){return k instanceof d?k:new d(function(m){m(k)})}
var d=void 0;return new (d||(d=Promise))(function(k,m){function f(l){try{e(b.next(l))}catch(g){m(g)}}function h(l){try{e(b["throw"](l))}catch(g){m(g)}}function e(l){l.done?k(l.value):c(l.value).then(f,h)}e((b=b.apply(a,[])).next())})},eb=function(){var a=Va,b=window.location.origin,c=Wa,d=Xa;this.state=0;this.F=a;this.Y=b;this.K=c;this.B=d},fb=function(a,b,c){this.S=a;this.H=b;this.l=c;this.ga=!1},gb=function(a,b){function c(k){return k instanceof d?k:new d(function(m){m(k)})}var d=void 0;return new (d||
(d=Promise))(function(k,m){function f(l){try{e(b.next(l))}catch(g){m(g)}}function h(l){try{e(b["throw"](l))}catch(g){m(g)}}function e(l){l.done?k(l.value):c(l.value).then(f,h)}e((b=b.apply(a,[])).next())})},hb=function(){var a=Va,b=window.location.origin,c=Wa,d=Xa;this.state=0;this.F=a;this.Y=b;this.K=c;this.B=d},ib=function(){var a=Error.apply(this,arguments);this.message=a.message;"stack"in a&&(this.stack=a.stack)},jb=function(){switch(Y.replace(/^.*?:\/\/sdk\.canva.*?\/(.*\.js)$/,"$1")){case "designbutton/v2/api.js":return 1;
case "kiosk.js":return 2;case "partnership.js":return 3;case "v2/beta/api.js":return 0;default:throw new ib;}},kb=function(a,b){function c(k){return k instanceof d?k:new d(function(m){m(k)})}var d=void 0;return new (d||(d=Promise))(function(k,m){function f(l){try{e(b.next(l))}catch(g){m(g)}}function h(l){try{e(b["throw"](l))}catch(g){m(g)}}function e(l){l.done?k(l.value):c(l.value).then(f,h)}e((b=b.apply(a,[])).next())})},lb=function(a){this.la=a},mb=function(a,b){function c(k){return k instanceof
d?k:new d(function(m){m(k)})}var d=void 0;return new (d||(d=Promise))(function(k,m){function f(l){try{e(b.next(l))}catch(g){m(g)}}function h(l){try{e(b["throw"](l))}catch(g){m(g)}}function e(l){l.done?k(l.value):c(l.value).then(f,h)}e((b=b.apply(a,[])).next())})},nb=function(a){this.la=a},ob=function(a){this.initialize=a},pb=function(a,b){var c=b.apiKey;b=b.autoAuthToken;a.Sa||(a.Sa=a.initialize({apiKey:c,autoAuthToken:b}));return a.Sa},qb=function(a,b){a=a[b];F(a,b+" callback is not found");E("function"===
typeof a,b+" is not a function: "+typeof a);return a},rb=function(a,b,c){b&&(F(a.querySelector('input[name="'+b+'"]'),'Input element with name equals to "'+b+'" is not found').value=c)},sb=function(a){this.window=window;this.v=a},tb=function(a){this.window=window;this.v=a},ub=function(a){this.window=window;this.v=a},vb=function(a,b){this.document=a;this.v=b},wb=function(a,b){this.document=a;this.v=b},xb=function(a){var b=document,c=new vb(b,a),d=new tb(a),k=new wb(b,a),m=new ub(a),f=new sb(a);return{aa:function(h){c.aa(h);
d.aa(h)},ba:function(h,e){k.ba(h,e);m.ba(h,e)},na:function(){f.na()}}},yb=function(a,b){function c(k){return k instanceof d?k:new d(function(m){m(k)})}var d=void 0;return new (d||(d=Promise))(function(k,m){function f(l){try{e(b.next(l))}catch(g){m(g)}}function h(l){try{e(b["throw"](l))}catch(g){m(g)}}function e(l){l.done?k(l.value):c(l.value).then(f,h)}e((b=b.apply(a,[])).next())})},zb=function(a){switch(a){case "large":return"EIT08g _58Jiow u_3oDw Wls18A _8EhpRA";case "default":return"IcdUrA _58Jiow u_3oDw Wls18A _8EhpRA";
case "small":return"bU0VTA _58Jiow u_3oDw Wls18A _8EhpRA";case "tiny":return"Xa2ohw _58Jiow u_3oDw Wls18A _8EhpRA";default:throw new G(a);}},Ab=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];return b.join(" ")},Bb=function(a,b,c){var d=this;this.element=a;this.v=b;this.Ra=c;this.tb=function(){return yb(d,function m(){var f=this,h;return A(m,function(e){h=Object.assign(Object.assign({},f.v),{designId:f.designId});f.Ra.hb(h,{onDesignOpen:f.aa,onDesignPublish:f.ba,onDesignClose:f.na});
e.C=0})})};this.aa=function(k){k=k.designId;var m,f;d.designId=k;null===(f=null===(m=d.va)||void 0===m?void 0:m.aa)||void 0===f?void 0:f.call(m,k)};this.ba=function(k){var m=k.exportUrl;k=k.designId;var f,h;null===(h=null===(f=d.va)||void 0===f?void 0:f.ba)||void 0===h?void 0:h.call(f,m,k)};this.na=function(){var k,m;null===(m=null===(k=d.va)||void 0===k?void 0:k.na)||void 0===m?void 0:m.call(k)};b.designId&&(this.designId=b.designId)},Cb=function(a,b){return a&&b.has(a)?a:"default"},Fb=function(a){a=
a.dataset;var b=Z(a,"designType","type"),c=a.designId;E(!!b!==!!c,"One and only one of design ID or design type must be provided.");return{apiKey:F(a.apiKey,"Empty apiKey is not allowed"),autoAuthToken:a.autoAuthToken,publishLabel:Z(a,"editorPublishLabel","publishLabel"),Ga:b,designId:c,size:Cb(a.buttonSize,Db),jb:Cb(a.buttonTheme,Eb),width:Z(a,"designWidth","width"),height:Z(a,"designHeight","height"),units:Z(a,"designUnits","units"),fb:Z(a,"onPublishUrlInput","input","designUrlInput"),eb:Z(a,"onPublishIdInput",
"idInput"),Va:a.onCloseCallback,cb:a.onPublishCallback,yb:a.urlCallback||a.publishCallback,fileType:Z(a,"exportFileType","fileType")}},Gb=function(a){a=a.dataset;var b=a.designType,c=a.designId;E(!!b!==!!c,"One and only one of design ID or design type must be provided.");return{apiKey:F(a.apiKey,"Empty apiKey is not allowed"),autoAuthToken:a.autoAuthToken,Ga:b,designId:c,width:a.designDimensionsWidth,height:a.designDimensionsHeight,units:a.designDimensionsUnits,publishLabel:a.editorPublishLabel,fileType:a.editorFileType,
size:Cb(a.buttonSize,Db),jb:Cb(a.buttonTheme,Eb),zb:a.onDesignOpen,Ab:a.onDesignOpenInputDesignId,cb:a.onDesignPublish,eb:a.onDesignPublishInputDesignId,fb:a.onDesignPublishInputExportUrl,Va:a.onDesignClose}},Hb=function(a){return"data-"+a.replace(/[A-Z]/g,function(b){return"-"+b.toLowerCase()})},Z=function(a,b,c){for(var d=[],k=2;k<arguments.length;++k)d[k-2]=arguments[k];(d=d.find(function(m){return void 0!==a[m]}))&&console.warn("[CanvaButton]: You are using "+Hb(d)+", which is obsolete and will be removed after the beta phase.  Please use "+
(Hb(b)+" instead"));return a[d||b]},Ib=function(a,b){function c(k){return k instanceof d?k:new d(function(m){m(k)})}var d=void 0;return new (d||(d=Promise))(function(k,m){function f(l){try{e(b.next(l))}catch(g){m(g)}}function h(l){try{e(b["throw"](l))}catch(g){m(g)}}function e(l){l.done?k(l.value):c(l.value).then(f,h)}e((b=b.apply(a,[])).next())})},Jb=function(a,b,c){return Ib(this,function k(){var m,f;return A(k,function(h){try{m=b(a);f=new Bb(a,m,c);f.va=xb(m);F(f.va,"Handler is not set");f.Ra.initialize(f.v);
var e=f.element,l=document.createElement("span"),g=document.createElement("span");g.className="vh-Z9g";l.setAttribute("dir","ltr");e.parentElement&&e.parentElement.replaceChild(l,e);l.appendChild(e);e.addEventListener("click",f.tb);var n=zb(f.v.size);a:{var p=f.v.jb;switch(p){case "default":var q="_-sjmGg";break a;case "dark":q="_0eJHmg";break a;case "light":q="YOby9A";break a;default:throw new G(p);}}e.className=Ab(n,q);e.insertBefore(g,e.firstChild);e.style.display=""}catch(t){return console.error("[CanvaButton] "+
t.message),h.return()}h.C=0})})},Lb=function(){var a=Kb.initialize,b=Array.from(document.body.querySelectorAll(".canva-design-button"));if(0!==b.length){var c=new lb(new ob(a));b.forEach(function(d){return Jb(d,Fb,c)})}},Nb=function(){var a=Mb.initialize,b=Array.from(document.body.querySelectorAll(".canva-design-button"));if(0!==b.length){var c=new nb(new ob(a));b.forEach(function(d){return Jb(d,Gb,c)})}},da="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},
ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},x=ba(this),Ob;if("function"==typeof Object.setPrototypeOf)Ob=Object.setPrototypeOf;else{var Pb;a:{var Qb={a:!0},Rb={};try{Rb.__proto__=Qb;Pb=Rb.a;break a}catch(a){}Pb=!1}Ob=Pb?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ea=Ob;ha.prototype.qa=function(a){this.Da=a};
ha.prototype.ua=function(a){this.U={Wa:a,ub:!0};this.C=this.W||this.Za};ha.prototype.return=function(a){this.U={return:a};this.C=this.Za};la.prototype.qa=function(a){ia(this.j);if(this.j.T)return ma(this,this.j.T.next,a,this.j.qa);this.j.qa(a);return na(this)};la.prototype.ua=function(a){ia(this.j);if(this.j.T)return ma(this,this.j.T["throw"],a,this.j.qa);this.j.ua(a);return na(this)};
y("Symbol",function(a){function b(k){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(k||"")+"_"+d++,k)}function c(k,m){this.lb=k;ca(this,"description",{configurable:!0,writable:!0,value:m})}if(a)return a;c.prototype.toString=function(){return this.lb};var d=0;return b});
y("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=x[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ca(d.prototype,a,{configurable:!0,writable:!0,value:function(){return qa(aa(this))}})}return a});y("Array.prototype.keys",function(a){return a?a:function(){return ra(this,function(b){return b})}});
y("WeakMap",function(a){function b(e){this.oa=(h+=Math.random()+1).toString();if(e){e=u(e);for(var l;!(l=e.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(e){var l=typeof e;return"object"===l&&null!==e||"function"===l}function k(e){if(!B(e,f)){var l=new c;ca(e,f,{value:l})}}function m(e){var l=Object[e];l&&(Object[e]=function(g){if(g instanceof c)return g;Object.isExtensible(g)&&k(g);return l(g)})}if(function(){if(!a||!Object.seal)return!1;try{var e=Object.seal({}),l=Object.seal({}),
g=new a([[e,2],[l,3]]);if(2!=g.get(e)||3!=g.get(l))return!1;g.delete(e);g.set(l,4);return!g.has(e)&&4==g.get(l)}catch(n){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();m("freeze");m("preventExtensions");m("seal");var h=0;b.prototype.set=function(e,l){if(!d(e))throw Error("Invalid WeakMap key");k(e);if(!B(e,f))throw Error("WeakMap key fail: "+e);e[f][this.oa]=l;return this};b.prototype.get=function(e){return d(e)&&B(e,f)?e[f][this.oa]:void 0};b.prototype.has=function(e){return d(e)&&B(e,
f)&&B(e[f],this.oa)};b.prototype.delete=function(e){return d(e)&&B(e,f)&&B(e[f],this.oa)?delete e[f][this.oa]:!1};return b});
y("Map",function(a){function b(){var h={};return h.N=h.next=h.head=h}function c(h,e){var l=h.M;return qa(function(){if(l){for(;l.head!=h.M;)l=l.N;for(;l.next!=l.head;)return l=l.next,{done:!1,value:e(l)};l=null}return{done:!0,value:void 0}})}function d(h,e){var l=e&&typeof e;"object"==l||"function"==l?m.has(e)?l=m.get(e):(l=""+ ++f,m.set(e,l)):l="p_"+e;var g=h.ma[l];if(g&&B(h.ma,l))for(h=0;h<g.length;h++){var n=g[h];if(e!==e&&n.key!==n.key||e===n.key)return{id:l,list:g,index:h,A:n}}return{id:l,list:g,
index:-1,A:void 0}}function k(h){this.ma={};this.M=b();this.size=0;if(h){h=u(h);for(var e;!(e=h.next()).done;)e=e.value,this.set(e[0],e[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),e=new a(u([[h,"s"]]));if("s"!=e.get(h)||1!=e.size||e.get({x:4})||e.set({x:4},"t")!=e||2!=e.size)return!1;var l=e.entries(),g=l.next();if(g.done||g.value[0]!=h||"s"!=g.value[1])return!1;g=l.next();return g.done||4!=g.value[0].x||
"t"!=g.value[1]||!l.next().done?!1:!0}catch(n){return!1}}())return a;var m=new WeakMap;k.prototype.set=function(h,e){h=0===h?0:h;var l=d(this,h);l.list||(l.list=this.ma[l.id]=[]);l.A?l.A.value=e:(l.A={next:this.M,N:this.M.N,head:this.M,key:h,value:e},l.list.push(l.A),this.M.N.next=l.A,this.M.N=l.A,this.size++);return this};k.prototype.delete=function(h){h=d(this,h);return h.A&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.ma[h.id],h.A.N.next=h.A.next,h.A.next.N=h.A.N,h.A.head=null,this.size--,
!0):!1};k.prototype.clear=function(){this.ma={};this.M=this.M.N=b();this.size=0};k.prototype.has=function(h){return!!d(this,h).A};k.prototype.get=function(h){return(h=d(this,h).A)&&h.value};k.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};k.prototype.keys=function(){return c(this,function(h){return h.key})};k.prototype.values=function(){return c(this,function(h){return h.value})};k.prototype.forEach=function(h,e){for(var l=this.entries(),g;!(g=l.next()).done;)g=g.value,
h.call(e,g[1],g[0],this)};k.prototype[Symbol.iterator]=k.prototype.entries;var f=0;return k});
y("Set",function(a){function b(c){this.I=new Map;if(c){c=u(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.I.size}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(u([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var k=d.entries(),m=k.next();if(m.done||m.value[0]!=c||m.value[1]!=c)return!1;m=k.next();return m.done||m.value[0]==c||4!=m.value[0].x||
m.value[1]!=m.value[0]?!1:k.next().done}catch(f){return!1}}())return a;b.prototype.add=function(c){c=0===c?0:c;this.I.set(c,c);this.size=this.I.size;return this};b.prototype.delete=function(c){c=this.I.delete(c);this.size=this.I.size;return c};b.prototype.clear=function(){this.I.clear();this.size=0};b.prototype.has=function(c){return this.I.has(c)};b.prototype.entries=function(){return this.I.entries()};b.prototype.values=function(){return this.I.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var k=this;this.I.forEach(function(m){return c.call(d,m,m,k)})};return b});y("Array.prototype.values",function(a){return a?a:function(){return ra(this,function(b,c){return c})}});var Sb="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var k in d)B(d,k)&&(a[k]=d[k])}return a};y("Object.assign",function(a){return a||Sb});
y("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});y("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var k=d.length;c=c||0;for(0>c&&(c=Math.max(c+k,0));c<k;c++){var m=d[c];if(m===b||Object.is(m,b))return!0}return!1}});
y("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(b,c||0)}});
y("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var k=[],m="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof m){b=m.call(b);for(var f=0;!(m=b.next()).done;)k.push(c.call(d,m.value,f++))}else for(m=b.length,f=0;f<m;f++)k.push(c.call(d,b[f],f));return k}});y("Array.prototype.entries",function(a){return a?a:function(){return ra(this,function(b,c){return[b,c]})}});
y("Promise",function(a){function b(f){this.ka=0;this.sa=void 0;this.ha=[];this.ab=!1;var h=this.Fa();try{f(h.resolve,h.reject)}catch(e){h.reject(e)}}function c(){this.P=null}function d(f){return f instanceof b?f:new b(function(h){h(f)})}if(a)return a;c.prototype.Ta=function(f){if(null==this.P){this.P=[];var h=this;this.Ua(function(){h.qb()})}this.P.push(f)};var k=x.setTimeout;c.prototype.Ua=function(f){k(f,0)};c.prototype.qb=function(){for(;this.P&&this.P.length;){var f=this.P;this.P=[];for(var h=
0;h<f.length;++h){var e=f[h];f[h]=null;try{e()}catch(l){this.ob(l)}}}this.P=null};c.prototype.ob=function(f){this.Ua(function(){throw f;})};b.prototype.Fa=function(){function f(l){return function(g){e||(e=!0,l.call(h,g))}}var h=this,e=!1;return{resolve:f(this.Db),reject:f(this.La)}};b.prototype.Db=function(f){if(f===this)this.La(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.Hb(f);else{a:switch(typeof f){case "object":var h=null!=f;break a;case "function":h=!0;break a;
default:h=!1}h?this.Cb(f):this.$a(f)}};b.prototype.Cb=function(f){var h=void 0;try{h=f.then}catch(e){this.La(e);return}"function"==typeof h?this.Ib(h,f):this.$a(f)};b.prototype.La=function(f){this.gb(2,f)};b.prototype.$a=function(f){this.gb(1,f)};b.prototype.gb=function(f,h){if(0!=this.ka)throw Error("Cannot settle("+f+", "+h+"): Promise already settled in state"+this.ka);this.ka=f;this.sa=h;2===this.ka&&this.Eb();this.rb()};b.prototype.Eb=function(){var f=this;k(function(){if(f.xb()){var h=x.console;
"undefined"!==typeof h&&h.error(f.sa)}},1)};b.prototype.xb=function(){if(this.ab)return!1;var f=x.CustomEvent,h=x.Event,e=x.dispatchEvent;if("undefined"===typeof e)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):"function"===typeof h?f=new h("unhandledrejection",{cancelable:!0}):(f=x.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.sa;return e(f)};b.prototype.rb=function(){if(null!=this.ha){for(var f=0;f<
this.ha.length;++f)m.Ta(this.ha[f]);this.ha=null}};var m=new c;b.prototype.Hb=function(f){var h=this.Fa();f.wa(h.resolve,h.reject)};b.prototype.Ib=function(f,h){var e=this.Fa();try{f.call(h,e.resolve,e.reject)}catch(l){e.reject(l)}};b.prototype.then=function(f,h){function e(p,q){return"function"==typeof p?function(t){try{l(p(t))}catch(w){g(w)}}:q}var l,g,n=new b(function(p,q){l=p;g=q});this.wa(e(f,l),e(h,g));return n};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.wa=function(f,
h){function e(){switch(l.ka){case 1:f(l.sa);break;case 2:h(l.sa);break;default:throw Error("Unexpected state: "+l.ka);}}var l=this;null==this.ha?m.Ta(e):this.ha.push(e);this.ab=!0};b.resolve=d;b.reject=function(f){return new b(function(h,e){e(f)})};b.race=function(f){return new b(function(h,e){for(var l=u(f),g=l.next();!g.done;g=l.next())d(g.value).wa(h,e)})};b.all=function(f){var h=u(f),e=h.next();return e.done?d([]):new b(function(l,g){function n(t){return function(w){p[t]=w;q--;0==q&&l(p)}}var p=
[],q=0;do p.push(void 0),q++,d(e.value).wa(n(p.length-1),g),e=h.next();while(!e.done)})};return b});y("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var k=d.length,m=0;m<k;m++){var f=d[m];if(b.call(c,f,m,d)){b=f;break a}}b=void 0}return b}});fa(G,Error);fa(wa,Error);var Tb=ya(function(){return[1,"B"]}),Ba=function(a){var b=xa(function(){var c=a(),d=Object.keys(c)[0],k=new Map,m=new Map;c=u(c[d]);for(var f=c.next();!f.done;f=c.next()){f=f.value;var h=f.sb()[d];if(!h||1!==h.type)throw new TypeError("Missing discriminator.");k.set(h.value,f);m.set(h.Ka,f);if(e&&e!==h.g)throw new TypeError("oneOf json keys are not consistent.");var e=h.g}if(!e)throw new TypeError("OneOf has no cases.");return{pb:d,wb:k,vb:e,Fb:m}});return{D:function(c,d){var k=b(),m=c[k.pb];k=k.wb.get(m);
if(!k)throw new TypeError("Unknown oneof deserialized case "+m+(d?"for property "+d:"")+".");return k.D(c)},u:function(c,d){var k=b(),m=c[k.vb];k=k.Fb.get(m);if(!k)throw new TypeError("Unknown oneof serialized case "+m+(d?"for property "+d:"")+".");return k.u(c)}}}(function(){return{type:[Ub,Vb,Wb,Xb,Yb,Zb,$b,Na,ac]}}),Ub=P(function(){return Object.assign(Object.assign({type:H("A","DESIGN_OPEN_EVENT")},{}),{designId:J("A"),designTitle:J("B")})}),bc=ya(function(){return[1,"A",2,"B"]}),Vb=P(function(){var a=
Object,b=a.assign,c=Object.assign({type:H("B","DESIGN_PUBLISH_EVENT")},{});return b.call(a,c,{exportUrl:J("A"),designId:J("B"),designTitle:J("D"),Kb:I("C"),Mb:K("E"),Lb:{type:9,g:"F",u:bc.u,D:bc.D,Ba:void 0}})}),Wb=P(function(){var a=Object,b=a.assign,c=Object.assign({type:H("C","DESIGN_BUTTON_CONFIG")},{});return b.call(a,c,{fileType:K("A"),minPages:I("G"),maxPages:I("B"),ib:{type:7,g:"C",Ba:void 0},productId:K("D"),productSizeOptionId:K("E"),partnerProductId:K("H"),publishEmail:K("F")})}),Xb=P(function(){return Object.assign(Object.assign({type:H("D",
"PRODUCT_SELECT_EVENT")},{}),{partnerProductId:J("A"),doctype:K("J"),category:J("B"),template:K("C"),width:I("D"),height:I("E"),units:K("F"),minPages:I("K"),maxPages:va("G"),productId:J("H"),productSizeOptionId:J("I")})}),Yb=P(function(){return Object.assign(Object.assign({type:H("E","ARTWORK_CREATE_EVENT")},{}),{artworkId:J("A"),artworkTitle:J("C"),previewImageSrc:J("B"),pageCount:va("D")})}),Zb=P(function(){return Object.assign({type:H("F","EDITOR_BACK_CLICK_EVENT")},{})}),$b=P(function(){return Object.assign(Object.assign({type:H("G",
"DESIGN_SELECT_EVENT")},{}),{designId:J("A"),minPages:I("D"),maxPages:va("B"),partnerProductId:J("C")})}),Na=P(function(){return Object.assign({type:H("I","IFRAME_HIDE_EVENT")},{})}),ac=P(function(){var a=Object,b=a.assign,c=Object.assign({type:H("H","ERROR_EVENT")},{});return b.call(a,c,{ea:{type:8,g:"A",u:Tb.u,D:Tb.D,default:void 0}})});za.prototype.J=function(){var a=this;this.mb(function(b){return Ca(a,b)})};r=Ea.prototype;r.J=function(){var a=this;Aa(this.S,function(b){return a.ra(b)});this.S.J();Ja(this.l,function(){var b;R(a.l);null===(b=a.onDesignClose)||void 0===b?void 0:b.call(a)});this.ga=!0};
r.ra=function(a){switch(a.type){case "DESIGN_OPEN_EVENT":this.l.ja();var b=new Wb({fileType:this.fileType});Ha(F(this.l.xa),b);b={};this.onDesignOpen&&this.onDesignOpen((b.designId=a.designId,b.designTitle=a.designTitle,b));break;case "DESIGN_PUBLISH_EVENT":R(this.l);b={};this.onDesignPublish&&this.onDesignPublish((b.exportUrl=a.exportUrl,b.designId=a.designId,b.designTitle=a.designTitle,b));break;case "ERROR_EVENT":if(this.onError)switch(a.ea){case 1:this.onError({statusCode:403});break;default:throw new G(a.ea);
}break;case "DESIGN_SELECT_EVENT":case "PRODUCT_SELECT_EVENT":case "ARTWORK_CREATE_EVENT":case "DESIGN_BUTTON_CONFIG":case "EDITOR_BACK_CLICK_EVENT":case "IFRAME_HIDE_EVENT":break;default:throw new G(a);}};r.G=function(a){Ka(this.l,a);La(this.l)};
r.createDesign=function(a){var b=a.designId,c=a.type,d=a.template,k=a.templateQuery,m=a.publishLabel,f=a.width,h=a.height,e=a.units,l=a.fileType;a=Da(a,"designId type template templateQuery publishLabel width height units fileType".split(" "));Q(this);Fa(this,a);this.fileType=void 0===l?"png":l;if(b)this.G(this.H.za({designId:b,type:c,publishLabel:m,width:f,height:h,units:e,ta:!(null===a||void 0===a||!a.onError)}));else if(f&&h||c)this.G(this.H.ya({type:c,template:d,templateQuery:k,width:f,height:h,
units:e,publishLabel:m,ta:!(null===a||void 0===a||!a.onError)}));else throw Error("Must specify one of: type, width & height, designId");};r.editDesign=function(a){var b=a.designId,c=a.publishLabel,d=a.fileType;a=Da(a,["designId","publishLabel","fileType"]);Q(this);Fa(this,a);this.fileType=void 0===d?"png":d;this.G(this.H.Ja({designId:b,publishLabel:c,ta:!(null===a||void 0===a||!a.onError)}))};var Ma=["transitionend","transitionEnd","webkitTransitionEnd"];var Pa="ar ar-AE ar-AR ar-AU ar-BH ar-DE ar-DK ar-DZ ar-EG ar-GB ar-ID ar-IL ar-IQ ar-JO ar-KW ar-LB ar-LY ar-MA ar-MR ar-OM ar-PS ar-QA ar-SA ar-SD ar-SO ar-SY ar-TN ar-TR ar-US ar-XB ar-YE fa fa-IR he he-GB he-IL he-IS he-US he-ZA pa pa-PK ckb ckb-US ckb-IQ ur ur-PK ug ug-CN".split(" ");W.prototype.Ja=function(a){var b=a.designId,c=a.publishLabel;a=a.ta;return this.O+V(S(U(U(U(U(T(),"action","editDesign"),"designId",b),"publishLabel",c),"supportDesignButtonErrorPage",a),this.R))};
W.prototype.ya=function(a){var b=a.type,c=a.template,d=a.publishLabel,k=a.width,m=a.height,f=a.units,h=a.templateQuery;a=a.ta;return this.O+V(S(U(U(U(U(U(U(U(U(U(T(),"action","createDesign"),"type",b),"template",c),"templateQuery",h),"publishLabel",d),"width",k),"height",m),"units",f),"supportDesignButtonErrorPage",a),this.R))};
W.prototype.za=function(a){var b=a.designId,c=a.type,d=a.publishLabel,k=a.width,m=a.height,f=a.units;a=a.ta;return this.O+V(S(U(U(U(U(U(U(U(U(T(),"action","createDesign"),"designId",b),"type",c),"width",k),"height",m),"units",f),"publishLabel",d),"supportDesignButtonErrorPage",a),this.R))};
x.Object.defineProperties(W.prototype,{R:{configurable:!0,enumerable:!0,get:function(){var a={};return a.apiMode="button",a.embed=!0,a.origin=this.origin,a._sdkVersion=this.Ea,a.autoAuthToken=this.autoAuthToken,a.apiKey=this.apiKey,a}}});Ya.prototype.initialize=function(a){var b=a.apiKey,c=a.autoAuthToken;return Ta(this,function k(){var m=this,f,h,e,l,g,n;return A(k,function(p){switch(p.C){case 1:return ua(0===m.state,"should only initialize once"),m.state=1,p.W=2,z(p,m.V(m.K),4);case 4:ja(p);break;case 2:throw f=ka(p),m.state=0,f;case 3:return h=Oa({B:m.B,dir:Qa()?"rtl":"ltr"}),e=new W(m.F,b,m.Y,"D2b_1.1.1",c),l=new za(function(q){return window.addEventListener("message",q)},m.F),g=new Ea(l,e,h),g.J(),document.body.appendChild(h.L),
n=m.Z(g),m.state=2,p.return(n)}})})};Ya.prototype.V=function(a){return Ta(this,function c(){return A(c,function(d){return d.return(new Promise(function(k,m){var f=document.createElement("link");f.rel="stylesheet";f.href=a;f.onload=function(){return k()};f.onerror=function(){return m(Error("failed to load css"))};document.body.appendChild(f)}))})})};
Ya.prototype.Z=function(a){return{createDesign:function(b){var c=b.onDesignClose,d=b.onDesignOpen,k=b.onDesignPublish,m=b.onError,f=b.onCreateCallback,h=b.onPublishCallback;b=Ua(b,"onDesignClose onDesignOpen onDesignPublish onError onCreateCallback onPublishCallback".split(" "));!d&&f&&(Za("api.createDesign({onCreateCallback:(designId)=>{}})","api.createDesign({onDesignOpen:({designId})=>{}})"),d=function(e){e=e.designId;f&&f(e)});!k&&h&&(Za("api.createDesign({onPublishCallback:(designId)=>{}})",
"api.createDesign({onDesignPublish:({designId, exportUrl})=>{}})"),k=function(e){var l=e.exportUrl;e=e.designId;h&&h(l,e)});a.createDesign(Object.assign(Object.assign({},b),{onDesignClose:c,onDesignOpen:d,onDesignPublish:k,onError:m}))},editDesign:function(b){var c=b.onDesignClose,d=b.onDesignOpen,k=b.onDesignPublish,m=b.onError,f=b.onOpenCallback,h=b.onPublishCallback;b=Ua(b,"onDesignClose onDesignOpen onDesignPublish onError onOpenCallback onPublishCallback".split(" "));!d&&f&&(Za("api.editDesign({onOpenCallback:(designId)=>{}})",
"api.createDesign({onDesignOpen:({designId})=>{}})"),d=function(e){e=e.designId;f&&f(e)});!k&&h&&(Za("api.editDesign({onPublishCallback:(designId)=>{}})","api.createDesign({onDesignPublish:({designId, exportUrl})=>{}})"),k=function(e){var l=e.exportUrl;e=e.designId;h&&h(l,e)});a.editDesign(Object.assign(Object.assign({},b),{onDesignClose:c,onDesignOpen:d,onDesignPublish:k,onError:m}))}}};
Ya.prototype.$=function(){var a=this;return{initialize:function(b,c){return"string"===typeof b?(Za("CanvaButton.initialize(apiKey"+(c?", autoAuthToken":"")+")",'CanvaButton.initialize({apiKey: "API-KEY"'+(c?', autoAuthToken: "AUTO-AUTH-TOKEN"':"")+"})"),a.initialize({apiKey:b,autoAuthToken:c})):a.initialize({apiKey:b.apiKey,autoAuthToken:b.autoAuthToken})}}};ab.prototype.initialize=function(a){var b=a.apiKey,c=a.autoAuthToken;return $a(this,function k(){var m=this,f,h,e,l,g,n;return A(k,function(p){switch(p.C){case 1:return ua(0===m.state,"should only initialize once"),m.state=1,p.W=2,z(p,m.V(m.K),4);case 4:ja(p);break;case 2:throw f=ka(p),m.state=0,f;case 3:return h=Oa({B:m.B,dir:Qa()?"rtl":"ltr"}),e=new W(m.F,b,m.Y,"D2_1.1.1",c),l=new za(function(q){return window.addEventListener("message",q)},m.F),g=new Ea(l,e,h),g.J(),document.body.appendChild(h.L),
n=m.Z(g),m.state=2,p.return(n)}})})};ab.prototype.V=function(a){return $a(this,function c(){return A(c,function(d){return d.return(new Promise(function(k,m){var f=document.createElement("link");f.rel="stylesheet";f.href=a;f.onload=function(){return k()};f.onerror=function(){return m(Error("failed to load css"))};document.body.appendChild(f)}))})})};
ab.prototype.Z=function(a){return{createDesign:function(b){var c,d,k,m,f;a.createDesign({designId:b.design.id,type:b.design.type,width:null===(c=b.design.dimensions)||void 0===c?void 0:c.width,height:null===(d=b.design.dimensions)||void 0===d?void 0:d.height,units:null===(k=b.design.dimensions)||void 0===k?void 0:k.units,template:b.design.template,publishLabel:null===(m=b.editor)||void 0===m?void 0:m.publishLabel,fileType:null===(f=b.editor)||void 0===f?void 0:f.fileType,onDesignOpen:b.onDesignOpen,
onDesignPublish:b.onDesignPublish,onDesignClose:b.onDesignClose,onError:b.onError})},editDesign:function(b){var c,d;a.editDesign({designId:b.design.id,publishLabel:null===(c=b.editor)||void 0===c?void 0:c.publishLabel,fileType:null===(d=b.editor)||void 0===d?void 0:d.fileType,onDesignOpen:b.onDesignOpen,onDesignPublish:b.onDesignPublish,onDesignClose:b.onDesignClose,onError:b.onError})}}};ab.prototype.$=function(){var a=this;return{initialize:function(b){return a.initialize({apiKey:b.apiKey,autoAuthToken:b.autoAuthToken})}}};r=bb.prototype;r.J=function(){var a=this;Aa(this.S,function(b){return a.ra(b)});this.S.J();Ja(this.l,function(){return R(a.l)});this.ga=!0};r.Ca=function(a){this.maxPages=a};
r.ra=function(a){switch(a.type){case "PRODUCT_SELECT_EVENT":sessionStorage&&(sessionStorage.setItem("canvaLastPartnerProductId",a.partnerProductId),sessionStorage.setItem("canvaLastProductId",a.productId),sessionStorage.setItem("canvaLastProductSizeOptionId",a.productSizeOptionId));var b={};this.onProductSelect&&this.onProductSelect((b.partnerProductId=a.partnerProductId,b.productId=a.productId,b.productSizeOptionId=a.productSizeOptionId,b.doctype=a.doctype,b.category=a.category,b.template=a.template,
b.width=a.width,b.height=a.height,b.units=a.units,b.maxPages=a.maxPages,b));break;case "DESIGN_SELECT_EVENT":b={};this.onDesignSelect&&this.onDesignSelect((b.designId=a.designId,b.maxPages=a.maxPages,b.partnerProductId=a.partnerProductId,b));break;case "ARTWORK_CREATE_EVENT":R(this.l);b={};this.onArtworkCreate&&this.onArtworkCreate((b.artworkId=a.artworkId,b.previewImageSrc=a.previewImageSrc,b.pageCount=a.pageCount,b));break;case "EDITOR_BACK_CLICK_EVENT":this.onBackClick&&this.onBackClick();break;
case "DESIGN_OPEN_EVENT":this.l.ja();b=this.maxPages?Number(this.maxPages):2;var c=(null===sessionStorage||void 0===sessionStorage?void 0:sessionStorage.getItem("canvaLastProductId"))||void 0,d=(null===sessionStorage||void 0===sessionStorage?void 0:sessionStorage.getItem("canvaLastProductSizeOptionId"))||void 0;b=new Wb({maxPages:b,ib:!!this.onBackClick,productId:c,productSizeOptionId:d,publishEmail:this.publishEmail});Ha(F(this.l.xa),b);b={};this.onDesignOpen&&this.onDesignOpen((b.designId=a.designId,
b.designTitle=a.designTitle,b));break;case "ERROR_EVENT":if(this.onError)switch(a.ea){case 1:this.onError({statusCode:403});break;default:throw new G(a.ea);}break;case "DESIGN_PUBLISH_EVENT":case "DESIGN_BUTTON_CONFIG":case "IFRAME_HIDE_EVENT":break;default:throw new G(a);}};r.G=function(a,b){b=void 0===b?!1:b;Ka(this.l,a);b?this.l.ja():La(this.l)};
r.createDesign=function(a){var b=a.doctype,c=a.category,d=a.type,k=a.designId,m=a.maxPages,f=a.partnerProductId,h=a.template,e=a.title,l=a.width,g=a.height,n=a.units,p=a.publishLabel,q=a.onArtworkCreate,t=a.onDesignOpen,w=a.onBackClick,C=a.onError;a=a.kiosk;Q(this);this.Ca(m);this.onArtworkCreate=q;this.onDesignOpen=t;this.onBackClick=w;this.onError=C;this.publishEmail=null===a||void 0===a?void 0:a.publishEmail;m=sessionStorage&&sessionStorage.getItem("canvaLastPartnerProductId")||"";k?this.G(this.H.za({doctype:b,
category:c,type:d,designId:k,partnerProductId:f||m,title:e,width:l,height:g,units:n,publishLabel:p,da:!!C})):this.G(this.H.ya({doctype:b,category:c,type:d,partnerProductId:f||m,template:h,title:e,width:l,height:g,units:n,publishLabel:p,da:!!C}))};r.showCatalog=function(a){var b=a.onProductSelect;a=a.onDesignSelect;Q(this);this.onProductSelect=b;this.onDesignSelect=a;this.G(cb(this.H,!!a),!0)};X.prototype.ya=function(a){var b=a.doctype,c=a.category,d=a.type,k=a.partnerProductId,m=a.template,f=a.title,h=a.width,e=a.height,l=a.units,g=a.publishLabel;a=a.da;return this.O+V(S(U(U(U(U(U(U(U(U(U(U(U(U(T(),"action","createDesign"),"doctype",b),"category",c),"type",d),"partnerProductId",k),"template",m),"title",f),"publishLabel",g),"width",h),"height",e),"units",l),"supportPartnershipErrorPage",a),this.R))};
X.prototype.za=function(a){var b=a.doctype,c=a.category,d=a.type,k=a.designId,m=a.partnerProductId,f=a.title,h=a.width,e=a.height,l=a.units,g=a.publishLabel;a=a.da;return this.O+V(S(U(U(U(U(U(U(U(U(U(U(U(U(T(),"action","createDesign"),"doctype",b),"category",c),"type",d),"designId",k),"partnerProductId",m),"title",f),"publishLabel",g),"width",h),"height",e),"units",l),"supportPartnershipErrorPage",a),this.R))};
X.prototype.Ja=function(a){var b=a.designId,c=a.da;a=a.publishLabel;return this.O+V(S(U(U(U(U(T(),"action","editDesign"),"designId",b),"publishLabel",a),"supportPartnershipErrorPage",c),this.R))};x.Object.defineProperties(X.prototype,{R:{configurable:!0,enumerable:!0,get:function(){var a={};return a.apiMode="partnership",a.embed=!0,a.origin=this.origin,a._sdkVersion=this.Ea,a.autoAuthToken=this.autoAuthToken,a.apiKey=this.apiKey,a}}});eb.prototype.initialize=function(a){var b=a.apiKey,c=a.autoAuthToken,d=a.container;return db(this,function m(){var f=this,h,e,l,g,n,p;return A(m,function(q){switch(q.C){case 1:return ua(0===f.state,"should only initialize once"),f.state=1,q.W=2,z(q,f.V(d,f.K),4);case 4:ja(q);break;case 2:throw h=ka(q),f.state=0,h;case 3:return e=Oa({B:f.B,dir:Qa()?"rtl":"ltr",Qa:null==d,Pa:null==d,Oa:!1}),l=new X(f.F,b,f.Y,"K1_1.1.1",c),g=new za(function(t){return window.addEventListener("message",t)},f.F),n=new bb(g,
l,e),n.J(),(d||document.body).appendChild(e.L),p=f.Z(n),f.state=2,q.return(p)}})})};eb.prototype.V=function(a,b){a=void 0===a?document.body:a;return db(this,function d(){return A(d,function(k){return k.return(new Promise(function(m,f){var h=document.createElement("link");h.rel="stylesheet";h.href=b;h.onload=function(){return m()};h.onerror=function(){return f(Error("failed to load css"))};a.appendChild(h)}))})})};eb.prototype.Z=function(a){return{createDesign:function(b){a.createDesign(b)},showCatalog:function(b){return a.showCatalog(b)}}};
eb.prototype.$=function(){var a=this;return{initialize:function(b){return a.initialize({apiKey:b.apiKey,autoAuthToken:b.autoAuthToken,container:b.container})}}};r=fb.prototype;r.J=function(){var a=this;Aa(this.S,function(b){return a.ra(b)});this.S.J();Ja(this.l,function(){var b;R(a.l);null===(b=a.onDesignClose)||void 0===b?void 0:b.call(a)});this.ga=!0};r.Ca=function(a){this.maxPages=a};
r.ra=function(a){switch(a.type){case "PRODUCT_SELECT_EVENT":sessionStorage&&(sessionStorage.setItem("canvaLastPartnerProductId",a.partnerProductId),sessionStorage.setItem("canvaLastProductId",a.productId),sessionStorage.setItem("canvaLastProductSizeOptionId",a.productSizeOptionId));var b={};this.onProductSelect&&this.onProductSelect((b.partnerProductId=a.partnerProductId,b.productId=a.productId,b.productSizeOptionId=a.productSizeOptionId,b.doctype=a.doctype,b.category=a.category,b.template=a.template,
b.width=a.width,b.height=a.height,b.units=a.units,b.minPages=a.minPages,b.maxPages=a.maxPages,b));break;case "DESIGN_SELECT_EVENT":b={};this.onDesignSelect&&this.onDesignSelect((b.designId=a.designId,b.minPages=a.minPages,b.maxPages=a.maxPages,b.partnerProductId=a.partnerProductId,b));break;case "ARTWORK_CREATE_EVENT":R(this.l);b={};this.onArtworkCreate&&this.onArtworkCreate((b.artworkId=a.artworkId,b.artworkTitle=a.artworkTitle,b.previewImageSrc=a.previewImageSrc,b.pageCount=a.pageCount,b));break;
case "EDITOR_BACK_CLICK_EVENT":this.onBackClick&&this.onBackClick();break;case "DESIGN_OPEN_EVENT":this.l.ja();b=this.minPages?Number(this.minPages):void 0;var c=this.maxPages?Number(this.maxPages):2,d=(null===sessionStorage||void 0===sessionStorage?void 0:sessionStorage.getItem("canvaLastProductId"))||void 0,k=(null===sessionStorage||void 0===sessionStorage?void 0:sessionStorage.getItem("canvaLastProductSizeOptionId"))||void 0;b=new Wb({minPages:b,maxPages:c,ib:!!this.onBackClick,productId:d,productSizeOptionId:k});
Ha(F(this.l.xa),b);b={};this.onDesignOpen&&this.onDesignOpen((b.designId=a.designId,b.designTitle=a.designTitle,b));break;case "ERROR_EVENT":if(this.onError)switch(a.ea){case 1:this.onError({statusCode:403});break;default:throw new G(a.ea);}break;case "DESIGN_PUBLISH_EVENT":case "DESIGN_BUTTON_CONFIG":case "IFRAME_HIDE_EVENT":break;default:throw new G(a);}};r.G=function(a,b){b=void 0===b?!1:b;Ka(this.l,a);b?this.l.ja():La(this.l)};
r.createDesign=function(a){var b=a.doctype,c=a.category,d=a.type,k=a.designId,m=a.minPages,f=a.maxPages,h=a.partnerProductId,e=a.template,l=a.title,g=a.width,n=a.height,p=a.units,q=a.publishLabel,t=a.onArtworkCreate,w=a.onDesignClose,C=a.onDesignOpen,M=a.onBackClick;a=a.onError;Q(this);this.minPages=m;this.Ca(f);this.onArtworkCreate=t;this.onDesignClose=w;this.onDesignOpen=C;this.onBackClick=M;this.onError=a;m=sessionStorage&&sessionStorage.getItem("canvaLastPartnerProductId")||"";k?this.G(this.H.za({doctype:b,
category:c,type:d,designId:k,partnerProductId:h||m,title:l,width:g,height:n,units:p,publishLabel:q,da:!!a})):this.G(this.H.ya({doctype:b,category:c,type:d,partnerProductId:h||m,template:e,title:l,width:g,height:n,units:p,publishLabel:q,da:!!a}))};
r.editDesign=function(a){var b=a.designId,c=a.minPages,d=a.maxPages,k=a.publishLabel,m=a.onArtworkCreate,f=a.onDesignClose,h=a.onDesignOpen,e=a.onBackClick;a=a.onError;Q(this);this.minPages=c;this.Ca(d);this.onArtworkCreate=m;this.onDesignClose=f;this.onDesignOpen=h;this.onBackClick=e;this.onError=a;this.G(this.H.Ja({designId:b,da:!!a,publishLabel:k}))};r.showCatalog=function(a){var b=a.onProductSelect;a=a.onDesignSelect;Q(this);this.onProductSelect=b;this.onDesignSelect=a;this.G(cb(this.H,!!a),!0)};hb.prototype.initialize=function(a){var b=a.apiKey,c=a.autoAuthToken,d=a.container;return gb(this,function m(){var f=this,h,e,l,g,n,p;return A(m,function(q){switch(q.C){case 1:return ua(0===f.state,"should only initialize once"),f.state=1,q.W=2,z(q,f.V(d,f.K),4);case 4:ja(q);break;case 2:throw h=ka(q),f.state=0,h;case 3:return e=Oa({B:f.B,dir:Qa()?"rtl":"ltr",Qa:null==d,Pa:null==d,Oa:!1}),l=new X(f.F,b,f.Y,"P1_1.1.1",c),g=new za(function(t){return window.addEventListener("message",t)},f.F),n=new fb(g,
l,e),n.J(),(d||document.body).appendChild(e.L),p=f.Z(n),f.state=2,q.return(p)}})})};hb.prototype.V=function(a,b){a=void 0===a?document.body:a;return gb(this,function d(){return A(d,function(k){return k.return(new Promise(function(m,f){var h=document.createElement("link");h.rel="stylesheet";h.href=b;h.onload=function(){return m()};h.onerror=function(){return f(Error("failed to load css"))};a.appendChild(h)}))})})};
hb.prototype.Z=function(a){return{createDesign:function(b){a.createDesign(b)},editDesign:function(b){a.editDesign(b)},showCatalog:function(b){return a.showCatalog(b)}}};hb.prototype.$=function(){var a=this;return{initialize:function(b){return a.initialize({apiKey:b.apiKey,autoAuthToken:b.autoAuthToken,container:b.container})}}};fa(ib,Error);lb.prototype.initialize=function(a){return kb(this,function c(){var d=this;return A(c,function(k){return z(k,pb(d.la,a),0)})})};
lb.prototype.hb=function(a,b){kb(this,function d(){var k=this,m,f,h,e,l,g,n,p,q,t,w,C,M;return A(d,function(D){if(1==D.C)return z(D,pb(k.la,a),2);m=D.Da;f=a;h=f.designId;e=f.Ga;l=f.publishLabel;g=f.width;n=f.height;p=f.units;q=f.fileType;t=b;w=t.onDesignOpen;C=t.onDesignPublish;M=t.onDesignClose;if(h)return m.editDesign({designId:h,publishLabel:l,fileType:q,onDesignPublish:C,onDesignClose:M}),D.return();m.createDesign({type:e,publishLabel:l,width:g?parseInt(g,10):void 0,height:n?parseInt(n,10):void 0,
units:"px"===p||"cm"===p||"mm"===p||"in"===p?p:void 0,fileType:q,onDesignOpen:w,onDesignPublish:C,onDesignClose:M});D.C=0})})};nb.prototype.initialize=function(a){return mb(this,function c(){var d=this;return A(c,function(k){return z(k,pb(d.la,a),0)})})};
nb.prototype.hb=function(a,b){mb(this,function d(){var k=this,m,f,h,e,l,g,n,p,q,t,w,C,M;return A(d,function(D){if(1==D.C)return z(D,pb(k.la,a),2);m=D.Da;f=a;h=f.designId;e=f.Ga;l=f.publishLabel;g=f.width;n=f.height;p=f.units;q=f.fileType;t=b;w=t.onDesignOpen;C=t.onDesignPublish;M=t.onDesignClose;if(h)return m.editDesign({design:{id:h},editor:{publishLabel:l,fileType:q},onDesignOpen:w,onDesignPublish:C,onDesignClose:M}),D.return();m.createDesign({design:{type:e,dimensions:g&&n?{width:parseInt(g,10),
height:parseInt(n,10),units:"px"===p||"cm"===p||"mm"===p||"in"===p?p:void 0}:void 0},editor:{publishLabel:l,fileType:q},onDesignOpen:w,onDesignPublish:C,onDesignClose:M});D.C=0})})};sb.prototype.na=function(){var a=this.v.Va;a&&qb(this.window,a)()};tb.prototype.aa=function(a){var b=this.v.zb;if(b){var c={};qb(this.window,b)((c.designId=a,c))}};ub.prototype.ba=function(a,b){var c=this.v.cb,d=this.v.yb;if(c){var k={};qb(this.window,c)((k.exportUrl=a,k.designId=b,k))}d&&(c=qb(this.window,d),console.warn('[CanvaButton]: You are using "callback(exportUrl,designId)", which is obsolete and will be removed after the beta phase. Please use "data-on-publish-callback" and "callback({exportUrl,designId})" instead'),c(a,b))};vb.prototype.aa=function(a){rb(this.document,this.v.Ab,a)};wb.prototype.ba=function(a,b){var c=this.v,d=c.eb;rb(this.document,c.fb,a);rb(this.document,d,b)};var Eb=new Set(["dark","light","default"]),Db=new Set(["large","default","small","tiny"]);a:{window.CanvaButton=void 0;var cc={};window.Canva=(cc.DesignButton=void 0,cc.Partnership=void 0,cc._Kiosk=void 0,cc);var Va,Wa,dc,Xa;try{var ec,fc=document.querySelector("script[src*=\\/\\/sdk\\.canva]"),gc=/^.*?:\/\/sdk\.canva.*?\/.*\.js$/,Y=window.CANVA_DESIGN_BUTTON_SDK_SOURCE||"";if(!(fc&&fc.src.match(gc)||""!==Y))throw new ib;var hc=!0;fc&&fc.src.match(gc)&&(hc=!1,Y=fc.src);var ic;ic=Y.replace(/^(.*?):\/\/sdk\.(canva.*?)\/.*$/,"$1://www.$2");var jc;jc=Y.replace(/^(.*)\.js$/,"$1.css");var kc=
hc?1:jb(),lc=Y.match(/^.*?:\/\/sdk\.canva[^.]*.(cn|com)\/.*$/);ec={F:ic,K:jc,nb:kc,B:lc&&"cn"===lc[1]?"china":"global"};Va=ec.F;Wa=ec.K;dc=ec.nb;Xa=ec.B}catch(a){if(a instanceof ib)console.error("[CanvaButton] Please import canva button SDK through the snippet provided at https://www.canva.com/button/documentation");else throw a;break a}switch(dc){case 1:var Mb=(new ab).$(),mc={};window.Canva=(mc.DesignButton=Mb,mc);Nb();break;case 0:var Kb=(new Ya).$();window.CanvaButton=Kb;var nc={};window.Canva=
(nc.DesignButton=Kb,nc);Lb();break;case 2:var oc={};window.Canva=(oc._Kiosk=(new eb).$(),oc);break;case 3:var pc={};window.Canva=(pc.Partnership=(new hb).$(),pc);break;default:throw new G(dc);}};
}).call(self, self._1cc3633c579a90cfdd895e64021e2163);
//# sourceMappingURL=sourcemaps/fe45c60c6f9ed580fa82ded817593c2c.js.map